reg children educ7 age agesq evermarr urban electric tv

In [21]:
import pandas as pd
import numpy as np
df = pd.read_csv('/Users/pranjal/Desktop/Causal-Inference/data/fertil2.csv')

In [22]:
df.head()

,mnthborn,yearborn,age,electric,radio,tv,bicycle,educ,ceb,agefbrth,...,agesq,urban,urb_educ,spirit,protest,catholic,frsthalf,educ0,evermarr,educ7
0,5,64,24,1.0,1.0,1.0,1.0,12,0,NaN,...,576,1,12,0,0,0,1,0,0,1
1,1,56,32,1.0,1.0,1.0,1.0,13,3,25.0,...,1024,1,13,0,0,0,1,0,1,1
2,7,58,30,1.0,0.0,0.0,0.0,5,1,27.0,...,900,1,5,1,0,0,0,0,1,0
3,11,45,42,1.0,0.0,1.0,0.0,4,3,17.0,...,1764,1,4,0,0,0,0,0,1,0
4,5,45,43,1.0,1.0,1.0,1.0,11,2,24.0,...,1849,1,11,0,1,0,1,0,1,1

In [23]:
cat = df.select_dtypes('object').columns
df = pd.get_dummies(df, columns = cat, drop_first = True)

In [25]:
df.head()

,mnthborn,yearborn,age,electric,radio,tv,bicycle,educ,ceb,agefbrth,...,agesq,urban,urb_educ,spirit,protest,catholic,frsthalf,educ0,evermarr,educ7
0,5,64,24,1.0,1.0,1.0,1.0,12,0,NaN,...,576,1,12,0,0,0,1,0,0,1
1,1,56,32,1.0,1.0,1.0,1.0,13,3,25.0,...,1024,1,13,0,0,0,1,0,1,1
2,7,58,30,1.0,0.0,0.0,0.0,5,1,27.0,...,900,1,5,1,0,0,0,0,1,0
3,11,45,42,1.0,0.0,1.0,0.0,4,3,17.0,...,1764,1,4,0,0,0,0,0,1,0
4,5,45,43,1.0,1.0,1.0,1.0,11,2,24.0,...,1849,1,11,0,1,0,1,0,1,1

In [26]:
outcome = 'children'
treatment = 'educ7'
rest = list(df.drop([outcome, treatment], axis = 1).columns)
#rest = ['age', 'evermarr', 'urban', 'electric', 'tv']
df = df[[outcome] + [treatment] + rest]

In [27]:
#import wooldridge
#df = wooldridge.data('jtrain3')
#df['avg'] = 0.5 * (df.re74+df.re75)
#df = df.dropna()
df = df.fillna(0)
#df = df[df.avg <= 15]
y = df[outcome]
d = df[treatment]
x = df[rest].astype('float')
print(df.shape)
df.head()

(4361, 28)

,children,educ7,mnthborn,yearborn,age,electric,radio,tv,bicycle,educ,...,heduc,agesq,urban,urb_educ,spirit,protest,catholic,frsthalf,educ0,evermarr
0,0,1,5,64,24,1.0,1.0,1.0,1.0,12,...,0.0,576,1,12,0,0,0,1,0,0
1,3,1,1,56,32,1.0,1.0,1.0,1.0,13,...,12.0,1024,1,13,0,0,0,1,0,1
2,1,0,7,58,30,1.0,0.0,0.0,0.0,5,...,7.0,900,1,5,1,0,0,0,0,1
3,2,0,11,45,42,1.0,0.0,1.0,0.0,4,...,11.0,1764,1,4,0,0,0,0,0,1
4,2,1,5,45,43,1.0,1.0,1.0,1.0,11,...,14.0,1849,1,11,0,1,0,1,0,1

In [28]:
# Simple Comparision of Means
import statsmodels.api as sm
mod = sm.OLS(y, sm.add_constant(np.c_[d], prepend=False))
res = mod.fit()
print(res.summary())
print(res.params[0])
print(res.bse[0])

                            OLS Regression Results
==============================================================================
Dep. Variable:               children   R-squared:                       0.157
Model:                            OLS   Adj. R-squared:                  0.157
Method:                 Least Squares   F-statistic:                     810.1
Date:                Mon, 05 Dec 2022   Prob (F-statistic):          1.39e-163
Time:                        01:46:07   Log-Likelihood:                -9297.7
No. Observations:                4361   AIC:                         1.860e+04
Df Residuals:                    4359   BIC:                         1.861e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -1.7701      0.062    -28.462      0.000      -1.892      -1.648
const          3.2513      0.046     70.137      0.000       3.160       3.342
==============================================================================
Omnibus:                      446.078   Durbin-Watson:                   1.993
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              604.073
Skew:                           0.833   Prob(JB):                    6.72e-132
Kurtosis:                       3.743   Cond. No.                         2.77
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
-1.7700683635967038
0.06219083785644475

In [29]:
# Pooled Regression Adjustment
import statsmodels.api as sm
mod = sm.OLS(y, sm.add_constant(np.c_[d, x], prepend=False))
res = mod.fit()
print(res.summary())
print(res.params[0])
print(res.bse[0])

                            OLS Regression Results
==============================================================================
Dep. Variable:               children   R-squared:                       0.959
Model:                            OLS   Adj. R-squared:                  0.959
Method:                 Least Squares   F-statistic:                     3751.
Date:                Mon, 05 Dec 2022   Prob (F-statistic):               0.00
Time:                        01:46:09   Log-Likelihood:                -2706.0
No. Observations:                4361   AIC:                             5468.
Df Residuals:                    4333   BIC:                             5647.
Df Model:                          27
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0170      0.025      0.682      0.496      -0.032       0.066
x2             0.0063      0.004      1.436      0.151      -0.002       0.015
x3             0.0391      0.024      1.623      0.105      -0.008       0.086
x4             0.0593      0.025      2.382      0.017       0.011       0.108
x5             0.0076      0.024      0.311      0.756      -0.040       0.055
x6             0.0197      0.016      1.227      0.220      -0.012       0.051
x7             0.0051      0.030      0.172      0.863      -0.053       0.063
x8             0.0349      0.016      2.202      0.028       0.004       0.066
x9            -0.0161      0.005     -3.287      0.001      -0.026      -0.007
x10            0.8908      0.005    181.978      0.000       0.881       0.900
x11            0.0042      0.001      3.784      0.000       0.002       0.006
x12           -0.0263      0.038     -0.694      0.488      -0.100       0.048
x13            0.0342      0.016      2.103      0.036       0.002       0.066
x14           -0.0004      0.003     -0.137      0.891      -0.006       0.005
x15           -0.0008      0.002     -0.357      0.721      -0.005       0.004
x16            0.0002      0.003      0.056      0.955      -0.005       0.006
x17           -0.0017      0.003     -0.542      0.588      -0.008       0.005
x18            0.0025      0.002      0.995      0.320      -0.002       0.007
x19           -0.0003      0.000     -3.095      0.002      -0.001      -0.000
x20           -0.1040      0.026     -3.928      0.000      -0.156      -0.052
x21            0.0130      0.004      3.469      0.001       0.006       0.020
x22           -0.0078      0.017     -0.446      0.656      -0.042       0.026
x23           -0.0109      0.020     -0.534      0.593      -0.051       0.029
x24           -0.0113      0.026     -0.435      0.663      -0.062       0.040
x25            0.0307      0.026      1.176      0.240      -0.020       0.082
x26           -0.1034      0.028     -3.695      0.000      -0.158      -0.049
x27            0.0845      0.157      0.537      0.591      -0.224       0.393
const         -3.6333      2.134     -1.703      0.089      -7.816       0.550
==============================================================================
Omnibus:                     3465.766   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           140667.713
Skew:                          -3.466   Prob(JB):                         0.00
Kurtosis:                      29.946   Cond. No.                     3.07e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.07e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
0.016985310972168138
0.024918664585917176

In [30]:
import numpy as np
from doubleml.datasets import make_plr_CCDDHNR2018
from doubleml import DoubleMLData

np.random.seed(1234)
dml_data_bonus = DoubleMLData(df, y_col=outcome,
                                  d_cols=treatment,
                                  x_cols=list(rest))
print(dml_data_bonus)
from sklearn.base import clone
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LassoCV
learner = RandomForestRegressor(n_estimators = 500, max_features = 'sqrt', max_depth= 6)
ml_l_bonus = clone(learner)
ml_m_bonus = clone(learner)
learner = LassoCV()
ml_l_sim = clone(learner)
ml_m_sim = clone(learner)
def non_orth_score(y, d, l_hat, m_hat, g_hat, smpls):
    u_hat = y - g_hat
    psi_a = -np.multiply(d, d)
    psi_b = np.multiply(d, u_hat)
    return psi_a, psi_b

from doubleml import DoubleMLPLR
np.random.seed(3141)
obj_dml_plr_bonus = DoubleMLPLR(dml_data_bonus, ml_l_bonus, ml_m_bonus)
obj_dml_plr_bonus.fit();
print(obj_dml_plr_bonus)

================== DoubleMLData Object ==================

------------------ Data summary      ------------------
Outcome variable: children
Treatment variable(s): ['educ7']
Covariates: ['mnthborn', 'yearborn', 'age', 'electric', 'radio', 'tv', 'bicycle', 'educ', 'ceb', 'agefbrth', 'knowmeth', 'usemeth', 'monthfm', 'yearfm', 'agefm', 'idlnchld', 'heduc', 'agesq', 'urban', 'urb_educ', 'spirit', 'protest', 'catholic', 'frsthalf', 'educ0', 'evermarr']
Instrument variable(s): None
No. Observations: 4361

------------------ DataFrame info    ------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4361 entries, 0 to 4360
Columns: 28 entries, children to evermarr
dtypes: float64(12), int64(16)
memory usage: 954.1 KB

================== DoubleMLPLR Object ==================

------------------ Data summary      ------------------
Outcome variable: children
Treatment variable(s): ['educ7']
Covariates: ['mnthborn', 'yearborn', 'age', 'electric', 'radio', 'tv', 'bicycle', 'educ', 'ceb', 'agefbrth', 'knowmeth', 'usemeth', 'monthfm', 'yearfm', 'agefm', 'idlnchld', 'heduc', 'agesq', 'urban', 'urb_educ', 'spirit', 'protest', 'catholic', 'frsthalf', 'educ0', 'evermarr']
Instrument variable(s): None
No. Observations: 4361

------------------ Score & algorithm ------------------
Score function: partialling out
DML algorithm: dml2

------------------ Machine learner   ------------------
Learner ml_l: RandomForestRegressor(max_depth=6, max_features='sqrt', n_estimators=500)
Learner ml_m: RandomForestRegressor(max_depth=6, max_features='sqrt', n_estimators=500)

------------------ Resampling        ------------------
No. folds: 5
No. repeated sample splits: 1
Apply cross-fitting: True

------------------ Fit summary       ------------------
           coef   std err         t    P>|t|     2.5 %    97.5 %
educ7  0.048738  0.127618  0.381907  0.70253 -0.201388  0.298864

In [31]:
import numpy as np
from doubleml.datasets import make_plr_CCDDHNR2018
from doubleml import DoubleMLData

np.random.seed(1234)
dml_data_bonus = DoubleMLData(df, y_col=outcome,
                                  d_cols=treatment,
                                  x_cols=list(rest))
print(dml_data_bonus)
from sklearn.base import clone
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LassoCV
learner = RandomForestRegressor(n_estimators = 100, max_features = 'sqrt', max_depth= 6)
ml_l_bonus = clone(learner)
ml_m_bonus = clone(learner)
learner = LassoCV()
ml_l_sim = clone(learner)
ml_m_sim = clone(learner)
def non_orth_score(y, d, l_hat, m_hat, g_hat, smpls):
    u_hat = y - g_hat
    psi_a = -np.multiply(d, d)
    psi_b = np.multiply(d, u_hat)
    return psi_a, psi_b

from doubleml import DoubleMLPLR
np.random.seed(3141)
obj_dml_plr_bonus = DoubleMLPLR(dml_data_bonus, ml_l_bonus, ml_m_bonus)
obj_dml_plr_bonus.fit();
print(obj_dml_plr_bonus)

================== DoubleMLData Object ==================

------------------ Data summary      ------------------
Outcome variable: children
Treatment variable(s): ['educ7']
Covariates: ['mnthborn', 'yearborn', 'age', 'electric', 'radio', 'tv', 'bicycle', 'educ', 'ceb', 'agefbrth', 'knowmeth', 'usemeth', 'monthfm', 'yearfm', 'agefm', 'idlnchld', 'heduc', 'agesq', 'urban', 'urb_educ', 'spirit', 'protest', 'catholic', 'frsthalf', 'educ0', 'evermarr']
Instrument variable(s): None
No. Observations: 4361

------------------ DataFrame info    ------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4361 entries, 0 to 4360
Columns: 28 entries, children to evermarr
dtypes: float64(12), int64(16)
memory usage: 954.1 KB

================== DoubleMLPLR Object ==================

------------------ Data summary      ------------------
Outcome variable: children
Treatment variable(s): ['educ7']
Covariates: ['mnthborn', 'yearborn', 'age', 'electric', 'radio', 'tv', 'bicycle', 'educ', 'ceb', 'agefbrth', 'knowmeth', 'usemeth', 'monthfm', 'yearfm', 'agefm', 'idlnchld', 'heduc', 'agesq', 'urban', 'urb_educ', 'spirit', 'protest', 'catholic', 'frsthalf', 'educ0', 'evermarr']
Instrument variable(s): None
No. Observations: 4361

------------------ Score & algorithm ------------------
Score function: partialling out
DML algorithm: dml2

------------------ Machine learner   ------------------
Learner ml_l: RandomForestRegressor(max_depth=6, max_features='sqrt')
Learner ml_m: RandomForestRegressor(max_depth=6, max_features='sqrt')

------------------ Resampling        ------------------
No. folds: 5
No. repeated sample splits: 1
Apply cross-fitting: True

------------------ Fit summary       ------------------
           coef   std err         t     P>|t|     2.5 %   97.5 %
educ7 -0.037464  0.112867 -0.331932  0.739941 -0.258678  0.18375

In [32]:
# DML regression - still yeilds unbiased estimate of ATE 
from econml.dml import LinearDML
est = LinearDML(random_state=45)
est.fit(y, d, X=None,W=x)
est.summary()

Coefficient Results:  X is None, please call intercept_inference to learn the constant!

<class 'econml.utilities.Summary'>
"""
                       CATE Intercept Results
====================================================================
               point_estimate stderr zstat  pvalue ci_lower ci_upper
--------------------------------------------------------------------
cate_intercept         -0.055  0.034 -1.634  0.102   -0.122    0.011
--------------------------------------------------------------------

<sub>A linear parametric conditional average treatment effect (CATE) model was fitted:
$Y = \Theta(X)\cdot T + g(X, W) + \epsilon$
where for every outcome $i$ and treatment $j$ the CATE $\Theta_{ij}(X)$ has the form:
$\Theta_{ij}(X) = X' coef_{ij} + cate\_intercept_{ij}$
Coefficient Results table portrays the $coef_{ij}$ parameter vector for each outcome $i$ and treatment $j$. Intercept Results table portrays the $cate\_intercept_{ij}$ parameter.</sub>
"""