In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('/Users/pranjal/Desktop/Causal-Inference/data/wage.csv')

In [ ]:
reg lwage exper expersq educ age kidslt6 kidsge6

In [2]:
df.head()

,inlf,hours,kidslt6,kidsge6,age,educ,wage,repwage,hushrs,husage,...,faminc,mtr,motheduc,fatheduc,unem,city,exper,nwifeinc,lwage,expersq
0,1,1610,1,0,32,12,3.3540,2.65,2708,34,...,16310,0.7215,12,7,5.0,0,14,10.910060,1.210154,196
1,1,1656,0,2,30,12,1.3889,2.65,2310,30,...,21800,0.6615,7,7,11.0,1,5,19.499981,0.328512,25
2,1,1980,1,3,35,12,4.5455,4.04,3072,40,...,21040,0.6915,12,7,5.0,0,15,12.039910,1.514138,225
3,1,456,0,3,34,12,1.0965,3.25,1920,53,...,7300,0.7815,7,7,5.0,0,6,6.799996,0.092123,36
4,1,1568,1,2,31,14,4.5918,3.60,2000,32,...,27300,0.6215,12,14,9.5,1,7,20.100058,1.524272,49

In [27]:
cat = df.select_dtypes('object').columns
df = pd.get_dummies(df, columns = cat, drop_first = True)

In [3]:
df.columns

Index(['inlf', 'hours', 'kidslt6', 'kidsge6', 'age', 'educ', 'wage', 'repwage',
       'hushrs', 'husage', 'huseduc', 'huswage', 'faminc', 'mtr', 'motheduc',
       'fatheduc', 'unem', 'city', 'exper', 'nwifeinc', 'lwage', 'expersq'],
      dtype='object')

In [11]:
outcome = 'lwage'
treatment = 'educ'
rest = list(df.drop([outcome, treatment], axis = 1).columns)
rest = ['exper','age', 'kidslt6', 'kidsge6']
df = df[[outcome] + [treatment] + rest]

In [12]:
#import wooldridge
#df = wooldridge.data('jtrain3')
#df['avg'] = 0.5 * (df.re74+df.re75)
#df = df.dropna()
df = df.fillna(0)
#df = df[df.avg <= 15]
y = df[outcome]
d = df[treatment]
x = df[rest].astype('float')
print(df.shape)
x.head()

(753, 6)

   exper   age  kidslt6  kidsge6
0   14.0  32.0      1.0      0.0
1    5.0  30.0      0.0      2.0
2   15.0  35.0      1.0      3.0
3    6.0  34.0      0.0      3.0
4    7.0  31.0      1.0      2.0

In [13]:
# Simple Comparision of Means
import statsmodels.api as sm
mod = sm.OLS(y, sm.add_constant(np.c_[d], prepend=False))
res = mod.fit()
print(res.summary())
print(res.params[0])
print(res.bse[0])

                            OLS Regression Results
==============================================================================
Dep. Variable:                  lwage   R-squared:                       0.098
Model:                            OLS   Adj. R-squared:                  0.097
Method:                 Least Squares   F-statistic:                     81.90
Date:                Mon, 05 Dec 2022   Prob (F-statistic):           1.21e-18
Time:                        02:07:26   Log-Likelihood:                -863.86
No. Observations:                 753   AIC:                             1732.
Df Residuals:                     751   BIC:                             1741.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.1104      0.012      9.050      0.000       0.086       0.134
const         -0.6804      0.152     -4.462      0.000      -0.980      -0.381
==============================================================================
Omnibus:                        8.036   Durbin-Watson:                   0.989
Prob(Omnibus):                  0.018   Jarque-Bera (JB):                8.204
Skew:                           0.253   Prob(JB):                       0.0165
Kurtosis:                       2.921   Cond. No.                         69.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
0.11043766214950582
0.012203463383868447

In [14]:
# Pooled Regression Adjustment
import statsmodels.api as sm
mod = sm.OLS(y, sm.add_constant(np.c_[d, x], prepend=False))
res = mod.fit()
print(res.summary())
print(res.params[0])
print(res.bse[0])

                            OLS Regression Results
==============================================================================
Dep. Variable:                  lwage   R-squared:                       0.250
Model:                            OLS   Adj. R-squared:                  0.245
Method:                 Least Squares   F-statistic:                     49.87
Date:                Mon, 05 Dec 2022   Prob (F-statistic):           1.32e-44
Time:                        02:07:27   Log-Likelihood:                -794.39
No. Observations:                 753   AIC:                             1601.
Df Residuals:                     747   BIC:                             1629.
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.1018      0.011      8.941      0.000       0.079       0.124
x2             0.0343      0.003      9.981      0.000       0.028       0.041
x3            -0.0209      0.004     -5.344      0.000      -0.029      -0.013
x4            -0.3359      0.054     -6.171      0.000      -0.443      -0.229
x5            -0.0031      0.022     -0.142      0.887      -0.045       0.039
const          0.0326      0.243      0.134      0.893      -0.444       0.510
==============================================================================
Omnibus:                       38.794   Durbin-Watson:                   1.317
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               78.697
Skew:                           0.320   Prob(JB):                     8.15e-18
Kurtosis:                       4.448   Cond. No.                         444.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
0.10179375407128076
0.011384649825607716

In [18]:
import numpy as np
from doubleml.datasets import make_plr_CCDDHNR2018
from doubleml import DoubleMLData

np.random.seed(1234)
dml_data_bonus = DoubleMLData(df, y_col=outcome,
                                  d_cols=treatment,
                                  x_cols=list(rest))
print(dml_data_bonus)
from sklearn.base import clone
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LassoCV
learner = RandomForestRegressor(n_estimators = 500, max_features = 'sqrt', max_depth= 8)
ml_l_bonus = clone(learner)
ml_m_bonus = clone(learner)
learner = LassoCV()
ml_l_sim = clone(learner)
ml_m_sim = clone(learner)
def non_orth_score(y, d, l_hat, m_hat, g_hat, smpls):
    u_hat = y - g_hat
    psi_a = -np.multiply(d, d)
    psi_b = np.multiply(d, u_hat)
    return psi_a, psi_b

from doubleml import DoubleMLPLR
np.random.seed(3141)
obj_dml_plr_bonus = DoubleMLPLR(dml_data_bonus, ml_l_bonus, ml_m_bonus)
obj_dml_plr_bonus.fit();
print(obj_dml_plr_bonus)

================== DoubleMLData Object ==================

------------------ Data summary      ------------------
Outcome variable: lwage
Treatment variable(s): ['educ']
Covariates: ['exper', 'age', 'kidslt6', 'kidsge6']
Instrument variable(s): None
No. Observations: 753

------------------ DataFrame info    ------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 753 entries, 0 to 752
Columns: 6 entries, lwage to kidsge6
dtypes: float64(1), int64(5)
memory usage: 35.4 KB

================== DoubleMLPLR Object ==================

------------------ Data summary      ------------------
Outcome variable: lwage
Treatment variable(s): ['educ']
Covariates: ['exper', 'age', 'kidslt6', 'kidsge6']
Instrument variable(s): None
No. Observations: 753

------------------ Score & algorithm ------------------
Score function: partialling out
DML algorithm: dml2

------------------ Machine learner   ------------------
Learner ml_l: RandomForestRegressor(max_depth=8, max_features='sqrt', n_estimators=500)
Learner ml_m: RandomForestRegressor(max_depth=8, max_features='sqrt', n_estimators=500)

------------------ Resampling        ------------------
No. folds: 5
No. repeated sample splits: 1
Apply cross-fitting: True

------------------ Fit summary       ------------------
          coef   std err         t         P>|t|     2.5 %    97.5 %
educ  0.101939  0.012081  8.437655  3.237668e-17  0.078259  0.125618

In [19]:
import numpy as np
from doubleml.datasets import make_plr_CCDDHNR2018
from doubleml import DoubleMLData

np.random.seed(1234)
dml_data_bonus = DoubleMLData(df, y_col=outcome,
                                  d_cols=treatment,
                                  x_cols=list(rest))
print(dml_data_bonus)
from sklearn.base import clone
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LassoCV
learner = RandomForestRegressor(n_estimators = 100, max_features = 'sqrt', max_depth= 6)
ml_l_bonus = clone(learner)
ml_m_bonus = clone(learner)
learner = LassoCV()
ml_l_sim = clone(learner)
ml_m_sim = clone(learner)
def non_orth_score(y, d, l_hat, m_hat, g_hat, smpls):
    u_hat = y - g_hat
    psi_a = -np.multiply(d, d)
    psi_b = np.multiply(d, u_hat)
    return psi_a, psi_b

from doubleml import DoubleMLPLR
np.random.seed(3141)
obj_dml_plr_bonus = DoubleMLPLR(dml_data_bonus, ml_l_bonus, ml_m_bonus)
obj_dml_plr_bonus.fit();
print(obj_dml_plr_bonus)

================== DoubleMLData Object ==================

------------------ Data summary      ------------------
Outcome variable: lwage
Treatment variable(s): ['educ']
Covariates: ['exper', 'age', 'kidslt6', 'kidsge6']
Instrument variable(s): None
No. Observations: 753

------------------ DataFrame info    ------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 753 entries, 0 to 752
Columns: 6 entries, lwage to kidsge6
dtypes: float64(1), int64(5)
memory usage: 35.4 KB

================== DoubleMLPLR Object ==================

------------------ Data summary      ------------------
Outcome variable: lwage
Treatment variable(s): ['educ']
Covariates: ['exper', 'age', 'kidslt6', 'kidsge6']
Instrument variable(s): None
No. Observations: 753

------------------ Score & algorithm ------------------
Score function: partialling out
DML algorithm: dml2

------------------ Machine learner   ------------------
Learner ml_l: RandomForestRegressor(max_depth=6, max_features='sqrt')
Learner ml_m: RandomForestRegressor(max_depth=6, max_features='sqrt')

------------------ Resampling        ------------------
No. folds: 5
No. repeated sample splits: 1
Apply cross-fitting: True

------------------ Fit summary       ------------------
          coef  std err         t         P>|t|     2.5 %    97.5 %
educ  0.101919  0.01191  8.557764  1.150775e-17  0.078577  0.125261

In [22]:
# DML regression - still yeilds unbiased estimate of ATE 
from econml.dml import LinearDML
est = LinearDML(random_state=45)
est.fit(y, d, X=None,W=x)
est.summary()

Coefficient Results:  X is None, please call intercept_inference to learn the constant!

<class 'econml.utilities.Summary'>
"""
                       CATE Intercept Results
===================================================================
               point_estimate stderr zstat pvalue ci_lower ci_upper
-------------------------------------------------------------------
cate_intercept          0.105  0.012 9.029    0.0    0.082    0.128
-------------------------------------------------------------------

<sub>A linear parametric conditional average treatment effect (CATE) model was fitted:
$Y = \Theta(X)\cdot T + g(X, W) + \epsilon$
where for every outcome $i$ and treatment $j$ the CATE $\Theta_{ij}(X)$ has the form:
$\Theta_{ij}(X) = X' coef_{ij} + cate\_intercept_{ij}$
Coefficient Results table portrays the $coef_{ij}$ parameter vector for each outcome $i$ and treatment $j$. Intercept Results table portrays the $cate\_intercept_{ij}$ parameter.</sub>
"""