In [129]:
import wooldridge
df = wooldridge.data('jtrain3')
df['avg'] = 0.5 * (df.re74+df.re75)
df = df.dropna()
#df = df[df.avg <= 15000]
y = df.re78
d = df.train
x = df[['age', 'educ', 'black', 'hisp', 'married', 're74', 're75']]
df.head()

,train,age,educ,black,hisp,married,re74,re75,unem75,unem74,...,agesq,trre74,trre75,trun74,trun75,avgre,travgre,unem78,em78,avg
0,1,37,11,1,0,1,0.0,0.0,1,1,...,1369,0.0,0.0,1,1,0.0,0.0,0,1,0.0
1,1,30,12,1,0,0,0.0,0.0,1,1,...,900,0.0,0.0,1,1,0.0,0.0,0,1,0.0
2,1,27,11,1,0,0,0.0,0.0,1,1,...,729,0.0,0.0,1,1,0.0,0.0,0,1,0.0
3,1,33,8,1,0,0,0.0,0.0,1,1,...,1089,0.0,0.0,1,1,0.0,0.0,0,1,0.0
4,1,22,9,1,0,0,0.0,0.0,1,1,...,484,0.0,0.0,1,1,0.0,0.0,0,1,0.0

In [130]:
# Simple Comparision of Means
import statsmodels.api as sm
mod = sm.OLS(y, sm.add_constant(np.c_[d], prepend=False))
res = mod.fit()
print(res.params[0])
print(res.bse[0])

-15.204775944240788
1.1546143554800263

In [131]:
# Pooled Regression Adjustment
import statsmodels.api as sm
mod = sm.OLS(y, sm.add_constant(np.c_[d, x], prepend=False))
res = mod.fit()
print(res.summary())
print(res.params[0])
print(res.bse[0])

                            OLS Regression Results
==============================================================================
Dep. Variable:                   re78   R-squared:                       0.586
Model:                            OLS   Adj. R-squared:                  0.585
Method:                 Least Squares   F-statistic:                     472.2
Date:                Sun, 04 Dec 2022   Prob (F-statistic):               0.00
Time:                        18:20:59   Log-Likelihood:                -9969.3
No. Observations:                2675   AIC:                         1.996e+04
Df Residuals:                    2666   BIC:                         2.001e+04
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.8598      0.908      0.947      0.344      -0.920       2.639
x2            -0.0815      0.021     -3.940      0.000      -0.122      -0.041
x3             0.5280      0.075      7.015      0.000       0.380       0.676
x4            -0.5427      0.494     -1.098      0.272      -1.512       0.426
x5             2.1656      1.092      1.983      0.048       0.024       4.307
x6             1.2203      0.586      2.083      0.037       0.072       2.369
x7             0.2779      0.028      9.952      0.000       0.223       0.333
x8             0.5681      0.028     20.615      0.000       0.514       0.622
const          0.7767      1.366      0.569      0.570      -1.901       3.455
==============================================================================
Omnibus:                      989.816   Durbin-Watson:                   1.845
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            21698.216
Skew:                           1.222   Prob(JB):                         0.00
Kurtosis:                      16.737   Cond. No.                         347.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
0.8597702772193843
0.9075768109039074

In [132]:
import numpy as np
from doubleml.datasets import make_plr_CCDDHNR2018
from doubleml import DoubleMLData

np.random.seed(1234)
dml_data_bonus = DoubleMLData(df, y_col='re78',
                                  d_cols='train',
                                  x_cols=['age','educ', 'black', 'hisp', 'married', 're74', 're75'])
print(dml_data_bonus)

from sklearn.base import clone
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LassoCV
learner = RandomForestRegressor(n_estimators = 500, max_features = 'sqrt', max_depth= 5)
ml_l_bonus = clone(learner)
ml_m_bonus = clone(learner)
learner = LassoCV()
ml_l_sim = clone(learner)
ml_m_sim = clone(learner)
def non_orth_score(y, d, l_hat, m_hat, g_hat, smpls):
    u_hat = y - g_hat
    psi_a = -np.multiply(d, d)
    psi_b = np.multiply(d, u_hat)
    return psi_a, psi_b

from doubleml import DoubleMLPLR
np.random.seed(3141)
obj_dml_plr_bonus = DoubleMLPLR(dml_data_bonus, ml_l_bonus, ml_m_bonus)
obj_dml_plr_bonus.fit();
print(obj_dml_plr_bonus)

================== DoubleMLData Object ==================

------------------ Data summary      ------------------
Outcome variable: re78
Treatment variable(s): ['train']
Covariates: ['age', 'educ', 'black', 'hisp', 'married', 're74', 're75']
Instrument variable(s): None
No. Observations: 2675

------------------ DataFrame info    ------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2675 entries, 0 to 2674
Columns: 21 entries, train to avg
dtypes: float64(8), int64(13)
memory usage: 439.0 KB

================== DoubleMLPLR Object ==================

------------------ Data summary      ------------------
Outcome variable: re78
Treatment variable(s): ['train']
Covariates: ['age', 'educ', 'black', 'hisp', 'married', 're74', 're75']
Instrument variable(s): None
No. Observations: 2675

------------------ Score & algorithm ------------------
Score function: partialling out
DML algorithm: dml2

------------------ Machine learner   ------------------
Learner ml_l: RandomForestRegressor(max_depth=5, max_features='sqrt', n_estimators=500)
Learner ml_m: RandomForestRegressor(max_depth=5, max_features='sqrt', n_estimators=500)

------------------ Resampling        ------------------
No. folds: 5
No. repeated sample splits: 1
Apply cross-fitting: True

------------------ Fit summary       ------------------
           coef   std err        t     P>|t|     2.5 %    97.5 %
train -0.513116  0.943524 -0.54383  0.586559 -2.362389  1.336157